# LOGGER
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(funcName)s - line %(lineno)d - %(message)s"
LOG_DIR = './logs'
LOG_FILE = './logs/app.log'

# DATA
DATA_DIR = './data'

# TOPIC
TOPIC = [
    'crypto', 'bitcoin', 
    'ethereum', 'dogecoin', 
    'bnb', 'binance', 
    'shiba', 'shib', 
    'shibainu', 'shibarmy', 
    'shibarmy', 'shibainucoin', 
    'blockchain', 'altcoins', 
    'litecoin', 'ripple', 
    'cardano', 'polkadot', 
    'solana', 'tezos', 
    'uniswap', 'defi', 
    'nft', 'smartcontract', 
    'cryptocurrencynews', 'cryptoexchange', 
    'cryptotrading', 'cryptowallet', 
    'hodl', 'cryptomining',
    'bitcoincash', 'eos', 
    'stellar', 'tron', 
    'monero', 'dash', 
    'cosmos', 'vechain', 
    'theta', 'matic', 
    'Chainlink', 'aave', 
    'compound', 'synthetix', 
    'maker', 'cryptoanalysis', 
    'cryptomemes', 'cryptogaming',
    'bitcoinprice', 'ethprice',
    'iam_preethi', 'CamiRusso',
    'sassal0x', 'elonmusk',
    'VitalikButerin', 'cz_binance',
    'officialmcafee', 'aantonop',
    'APompliano', 'brian_armstrong',
    'rogerkver', 'gavinandresen',
    'TimDraper', 'SatoshiLite',
    'justinsuntron', 'IOHK_Charles',
    'laurashin', 'haydentiff',
    'ErikVoorhees', 'novogratz',
    'krakenfx', 'binance',
    'CoinDesk', 'Cointelegraph',
    'MessariCrypto', 'cryptocom',
    'CoinMarketCap', 'coindeskmarkets',
    'TheBlock__', 'decryptmedia',
    'BTCTN', 'czymez',
    'CamiRusso', 'sassal0x',
    'bendavenport', 'lwsnbaker',
    'crypto_bobby', 'udiWertheimer',
    'elonmusk', 'NickSzabo4',
    'aantonop', 'laurashin',
    'elonmusk', 'udiWertheimer',
    'gavofyork', 'danheld','elonmusk', 'VitalikButerin',
    'cz_binance', 'officialmcafee',
    'aantonop', 'APompliano',
    'brian_armstrong', 'rogerkver',
    'gavinandresen', 'TimDraper',
    'SatoshiLite', 'justinsuntron',
    'IOHK_Charles', 'laurashin',
    'haydentiff', 'ErikVoorhees',
    'novogratz', 'krakenfx',
    'binance', 'CoinDesk',
    'Cointelegraph', 'MessariCrypto',
    'cryptocom', 'CoinMarketCap',
    'coindeskmarkets', 'TheBlock__',
    'decryptmedia', 'BTCTN'
]